package com.tushu.pojo;

public class Bumen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.utype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String utype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bumen.btype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String btype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.id
     *
     * @return the value of bumen.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.id
     *
     * @param id the value for bumen.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.uid
     *
     * @return the value of bumen.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.uid
     *
     * @param uid the value for bumen.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.uname
     *
     * @return the value of bumen.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.uname
     *
     * @param uname the value for bumen.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.utype
     *
     * @return the value of bumen.utype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.utype
     *
     * @param utype the value for bumen.utype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUtype(String utype) {
        this.utype = utype == null ? null : utype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bumen.btype
     *
     * @return the value of bumen.btype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getBtype() {
        return btype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bumen.btype
     *
     * @param btype the value for bumen.btype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setBtype(String btype) {
        this.btype = btype == null ? null : btype.trim();
    }
}