package com.tushu.pojo;

public class Goumai {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goumai.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goumai.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goumai.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goumai.sname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String sname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goumai.id
     *
     * @return the value of goumai.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goumai.id
     *
     * @param id the value for goumai.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goumai.uid
     *
     * @return the value of goumai.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goumai.uid
     *
     * @param uid the value for goumai.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goumai.uname
     *
     * @return the value of goumai.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goumai.uname
     *
     * @param uname the value for goumai.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goumai.sname
     *
     * @return the value of goumai.sname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goumai.sname
     *
     * @param sname the value for goumai.sname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }
}