package com.tushu.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JieyueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public JieyueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andTbianhaoIsNull() {
            addCriterion("tbianhao is null");
            return (Criteria) this;
        }

        public Criteria andTbianhaoIsNotNull() {
            addCriterion("tbianhao is not null");
            return (Criteria) this;
        }

        public Criteria andTbianhaoEqualTo(Integer value) {
            addCriterion("tbianhao =", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoNotEqualTo(Integer value) {
            addCriterion("tbianhao <>", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoGreaterThan(Integer value) {
            addCriterion("tbianhao >", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoGreaterThanOrEqualTo(Integer value) {
            addCriterion("tbianhao >=", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoLessThan(Integer value) {
            addCriterion("tbianhao <", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoLessThanOrEqualTo(Integer value) {
            addCriterion("tbianhao <=", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoIn(List<Integer> values) {
            addCriterion("tbianhao in", values, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoNotIn(List<Integer> values) {
            addCriterion("tbianhao not in", values, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoBetween(Integer value1, Integer value2) {
            addCriterion("tbianhao between", value1, value2, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoNotBetween(Integer value1, Integer value2) {
            addCriterion("tbianhao not between", value1, value2, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTtypeIsNull() {
            addCriterion("ttype is null");
            return (Criteria) this;
        }

        public Criteria andTtypeIsNotNull() {
            addCriterion("ttype is not null");
            return (Criteria) this;
        }

        public Criteria andTtypeEqualTo(String value) {
            addCriterion("ttype =", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotEqualTo(String value) {
            addCriterion("ttype <>", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeGreaterThan(String value) {
            addCriterion("ttype >", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeGreaterThanOrEqualTo(String value) {
            addCriterion("ttype >=", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeLessThan(String value) {
            addCriterion("ttype <", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeLessThanOrEqualTo(String value) {
            addCriterion("ttype <=", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeLike(String value) {
            addCriterion("ttype like", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotLike(String value) {
            addCriterion("ttype not like", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeIn(List<String> values) {
            addCriterion("ttype in", values, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotIn(List<String> values) {
            addCriterion("ttype not in", values, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeBetween(String value1, String value2) {
            addCriterion("ttype between", value1, value2, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotBetween(String value1, String value2) {
            addCriterion("ttype not between", value1, value2, "ttype");
            return (Criteria) this;
        }

        public Criteria andTnameIsNull() {
            addCriterion("tname is null");
            return (Criteria) this;
        }

        public Criteria andTnameIsNotNull() {
            addCriterion("tname is not null");
            return (Criteria) this;
        }

        public Criteria andTnameEqualTo(String value) {
            addCriterion("tname =", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotEqualTo(String value) {
            addCriterion("tname <>", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameGreaterThan(String value) {
            addCriterion("tname >", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameGreaterThanOrEqualTo(String value) {
            addCriterion("tname >=", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameLessThan(String value) {
            addCriterion("tname <", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameLessThanOrEqualTo(String value) {
            addCriterion("tname <=", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameLike(String value) {
            addCriterion("tname like", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotLike(String value) {
            addCriterion("tname not like", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameIn(List<String> values) {
            addCriterion("tname in", values, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotIn(List<String> values) {
            addCriterion("tname not in", values, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameBetween(String value1, String value2) {
            addCriterion("tname between", value1, value2, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotBetween(String value1, String value2) {
            addCriterion("tname not between", value1, value2, "tname");
            return (Criteria) this;
        }

        public Criteria andJdateIsNull() {
            addCriterion("jdate is null");
            return (Criteria) this;
        }

        public Criteria andJdateIsNotNull() {
            addCriterion("jdate is not null");
            return (Criteria) this;
        }

        public Criteria andJdateEqualTo(Date value) {
            addCriterion("jdate =", value, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateNotEqualTo(Date value) {
            addCriterion("jdate <>", value, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateGreaterThan(Date value) {
            addCriterion("jdate >", value, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateGreaterThanOrEqualTo(Date value) {
            addCriterion("jdate >=", value, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateLessThan(Date value) {
            addCriterion("jdate <", value, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateLessThanOrEqualTo(Date value) {
            addCriterion("jdate <=", value, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateIn(List<Date> values) {
            addCriterion("jdate in", values, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateNotIn(List<Date> values) {
            addCriterion("jdate not in", values, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateBetween(Date value1, Date value2) {
            addCriterion("jdate between", value1, value2, "jdate");
            return (Criteria) this;
        }

        public Criteria andJdateNotBetween(Date value1, Date value2) {
            addCriterion("jdate not between", value1, value2, "jdate");
            return (Criteria) this;
        }

        public Criteria andJolddateIsNull() {
            addCriterion("jolddate is null");
            return (Criteria) this;
        }

        public Criteria andJolddateIsNotNull() {
            addCriterion("jolddate is not null");
            return (Criteria) this;
        }

        public Criteria andJolddateEqualTo(Date value) {
            addCriterion("jolddate =", value, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateNotEqualTo(Date value) {
            addCriterion("jolddate <>", value, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateGreaterThan(Date value) {
            addCriterion("jolddate >", value, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateGreaterThanOrEqualTo(Date value) {
            addCriterion("jolddate >=", value, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateLessThan(Date value) {
            addCriterion("jolddate <", value, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateLessThanOrEqualTo(Date value) {
            addCriterion("jolddate <=", value, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateIn(List<Date> values) {
            addCriterion("jolddate in", values, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateNotIn(List<Date> values) {
            addCriterion("jolddate not in", values, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateBetween(Date value1, Date value2) {
            addCriterion("jolddate between", value1, value2, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJolddateNotBetween(Date value1, Date value2) {
            addCriterion("jolddate not between", value1, value2, "jolddate");
            return (Criteria) this;
        }

        public Criteria andJtypeIsNull() {
            addCriterion("jtype is null");
            return (Criteria) this;
        }

        public Criteria andJtypeIsNotNull() {
            addCriterion("jtype is not null");
            return (Criteria) this;
        }

        public Criteria andJtypeEqualTo(String value) {
            addCriterion("jtype =", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotEqualTo(String value) {
            addCriterion("jtype <>", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeGreaterThan(String value) {
            addCriterion("jtype >", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeGreaterThanOrEqualTo(String value) {
            addCriterion("jtype >=", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeLessThan(String value) {
            addCriterion("jtype <", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeLessThanOrEqualTo(String value) {
            addCriterion("jtype <=", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeLike(String value) {
            addCriterion("jtype like", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotLike(String value) {
            addCriterion("jtype not like", value, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeIn(List<String> values) {
            addCriterion("jtype in", values, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotIn(List<String> values) {
            addCriterion("jtype not in", values, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeBetween(String value1, String value2) {
            addCriterion("jtype between", value1, value2, "jtype");
            return (Criteria) this;
        }

        public Criteria andJtypeNotBetween(String value1, String value2) {
            addCriterion("jtype not between", value1, value2, "jtype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jieyue
     *
     * @mbggenerated do_not_delete_during_merge Thu May 26 10:42:14 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}