package com.tushu.pojo;

import java.util.Date;

public class Jieyue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.tbianhao
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer tbianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.ttype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String ttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.tname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.jdate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Date jdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.jolddate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Date jolddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jieyue.jtype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String jtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.id
     *
     * @return the value of jieyue.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.id
     *
     * @param id the value for jieyue.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.uid
     *
     * @return the value of jieyue.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.uid
     *
     * @param uid the value for jieyue.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.tbianhao
     *
     * @return the value of jieyue.tbianhao
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getTbianhao() {
        return tbianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.tbianhao
     *
     * @param tbianhao the value for jieyue.tbianhao
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTbianhao(Integer tbianhao) {
        this.tbianhao = tbianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.ttype
     *
     * @return the value of jieyue.ttype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTtype() {
        return ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.ttype
     *
     * @param ttype the value for jieyue.ttype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTtype(String ttype) {
        this.ttype = ttype == null ? null : ttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.tname
     *
     * @return the value of jieyue.tname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.tname
     *
     * @param tname the value for jieyue.tname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.jdate
     *
     * @return the value of jieyue.jdate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Date getJdate() {
        return jdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.jdate
     *
     * @param jdate the value for jieyue.jdate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setJdate(Date jdate) {
        this.jdate = jdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.jolddate
     *
     * @return the value of jieyue.jolddate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Date getJolddate() {
        return jolddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.jolddate
     *
     * @param jolddate the value for jieyue.jolddate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setJolddate(Date jolddate) {
        this.jolddate = jolddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jieyue.jtype
     *
     * @return the value of jieyue.jtype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getJtype() {
        return jtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jieyue.jtype
     *
     * @param jtype the value for jieyue.jtype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setJtype(String jtype) {
        this.jtype = jtype == null ? null : jtype.trim();
    }
}