package com.tushu.pojo;

public class Shenqinggoumai {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenqinggoumai.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenqinggoumai.stype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String stype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenqinggoumai.sname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenqinggoumai.sauthor
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String sauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenqinggoumai.schubanshe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String schubanshe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenqinggoumai.szhuangtai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String szhuangtai;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenqinggoumai.id
     *
     * @return the value of shenqinggoumai.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenqinggoumai.id
     *
     * @param id the value for shenqinggoumai.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenqinggoumai.stype
     *
     * @return the value of shenqinggoumai.stype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenqinggoumai.stype
     *
     * @param stype the value for shenqinggoumai.stype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenqinggoumai.sname
     *
     * @return the value of shenqinggoumai.sname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenqinggoumai.sname
     *
     * @param sname the value for shenqinggoumai.sname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenqinggoumai.sauthor
     *
     * @return the value of shenqinggoumai.sauthor
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getSauthor() {
        return sauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenqinggoumai.sauthor
     *
     * @param sauthor the value for shenqinggoumai.sauthor
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setSauthor(String sauthor) {
        this.sauthor = sauthor == null ? null : sauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenqinggoumai.schubanshe
     *
     * @return the value of shenqinggoumai.schubanshe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getSchubanshe() {
        return schubanshe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenqinggoumai.schubanshe
     *
     * @param schubanshe the value for shenqinggoumai.schubanshe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setSchubanshe(String schubanshe) {
        this.schubanshe = schubanshe == null ? null : schubanshe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenqinggoumai.szhuangtai
     *
     * @return the value of shenqinggoumai.szhuangtai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getSzhuangtai() {
        return szhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenqinggoumai.szhuangtai
     *
     * @param szhuangtai the value for shenqinggoumai.szhuangtai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setSzhuangtai(String szhuangtai) {
        this.szhuangtai = szhuangtai == null ? null : szhuangtai.trim();
    }
}