package com.tushu.pojo;

import java.util.ArrayList;
import java.util.List;

public class ShenqinggoumaiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public ShenqinggoumaiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStypeIsNull() {
            addCriterion("stype is null");
            return (Criteria) this;
        }

        public Criteria andStypeIsNotNull() {
            addCriterion("stype is not null");
            return (Criteria) this;
        }

        public Criteria andStypeEqualTo(String value) {
            addCriterion("stype =", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotEqualTo(String value) {
            addCriterion("stype <>", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThan(String value) {
            addCriterion("stype >", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThanOrEqualTo(String value) {
            addCriterion("stype >=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThan(String value) {
            addCriterion("stype <", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThanOrEqualTo(String value) {
            addCriterion("stype <=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLike(String value) {
            addCriterion("stype like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotLike(String value) {
            addCriterion("stype not like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeIn(List<String> values) {
            addCriterion("stype in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotIn(List<String> values) {
            addCriterion("stype not in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeBetween(String value1, String value2) {
            addCriterion("stype between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotBetween(String value1, String value2) {
            addCriterion("stype not between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andSnameIsNull() {
            addCriterion("sname is null");
            return (Criteria) this;
        }

        public Criteria andSnameIsNotNull() {
            addCriterion("sname is not null");
            return (Criteria) this;
        }

        public Criteria andSnameEqualTo(String value) {
            addCriterion("sname =", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotEqualTo(String value) {
            addCriterion("sname <>", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThan(String value) {
            addCriterion("sname >", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThanOrEqualTo(String value) {
            addCriterion("sname >=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThan(String value) {
            addCriterion("sname <", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThanOrEqualTo(String value) {
            addCriterion("sname <=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLike(String value) {
            addCriterion("sname like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotLike(String value) {
            addCriterion("sname not like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameIn(List<String> values) {
            addCriterion("sname in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotIn(List<String> values) {
            addCriterion("sname not in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameBetween(String value1, String value2) {
            addCriterion("sname between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotBetween(String value1, String value2) {
            addCriterion("sname not between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSauthorIsNull() {
            addCriterion("sauthor is null");
            return (Criteria) this;
        }

        public Criteria andSauthorIsNotNull() {
            addCriterion("sauthor is not null");
            return (Criteria) this;
        }

        public Criteria andSauthorEqualTo(String value) {
            addCriterion("sauthor =", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorNotEqualTo(String value) {
            addCriterion("sauthor <>", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorGreaterThan(String value) {
            addCriterion("sauthor >", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorGreaterThanOrEqualTo(String value) {
            addCriterion("sauthor >=", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorLessThan(String value) {
            addCriterion("sauthor <", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorLessThanOrEqualTo(String value) {
            addCriterion("sauthor <=", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorLike(String value) {
            addCriterion("sauthor like", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorNotLike(String value) {
            addCriterion("sauthor not like", value, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorIn(List<String> values) {
            addCriterion("sauthor in", values, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorNotIn(List<String> values) {
            addCriterion("sauthor not in", values, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorBetween(String value1, String value2) {
            addCriterion("sauthor between", value1, value2, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSauthorNotBetween(String value1, String value2) {
            addCriterion("sauthor not between", value1, value2, "sauthor");
            return (Criteria) this;
        }

        public Criteria andSchubansheIsNull() {
            addCriterion("schubanshe is null");
            return (Criteria) this;
        }

        public Criteria andSchubansheIsNotNull() {
            addCriterion("schubanshe is not null");
            return (Criteria) this;
        }

        public Criteria andSchubansheEqualTo(String value) {
            addCriterion("schubanshe =", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheNotEqualTo(String value) {
            addCriterion("schubanshe <>", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheGreaterThan(String value) {
            addCriterion("schubanshe >", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheGreaterThanOrEqualTo(String value) {
            addCriterion("schubanshe >=", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheLessThan(String value) {
            addCriterion("schubanshe <", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheLessThanOrEqualTo(String value) {
            addCriterion("schubanshe <=", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheLike(String value) {
            addCriterion("schubanshe like", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheNotLike(String value) {
            addCriterion("schubanshe not like", value, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheIn(List<String> values) {
            addCriterion("schubanshe in", values, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheNotIn(List<String> values) {
            addCriterion("schubanshe not in", values, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheBetween(String value1, String value2) {
            addCriterion("schubanshe between", value1, value2, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSchubansheNotBetween(String value1, String value2) {
            addCriterion("schubanshe not between", value1, value2, "schubanshe");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiIsNull() {
            addCriterion("szhuangtai is null");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiIsNotNull() {
            addCriterion("szhuangtai is not null");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiEqualTo(String value) {
            addCriterion("szhuangtai =", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiNotEqualTo(String value) {
            addCriterion("szhuangtai <>", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiGreaterThan(String value) {
            addCriterion("szhuangtai >", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiGreaterThanOrEqualTo(String value) {
            addCriterion("szhuangtai >=", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiLessThan(String value) {
            addCriterion("szhuangtai <", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiLessThanOrEqualTo(String value) {
            addCriterion("szhuangtai <=", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiLike(String value) {
            addCriterion("szhuangtai like", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiNotLike(String value) {
            addCriterion("szhuangtai not like", value, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiIn(List<String> values) {
            addCriterion("szhuangtai in", values, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiNotIn(List<String> values) {
            addCriterion("szhuangtai not in", values, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiBetween(String value1, String value2) {
            addCriterion("szhuangtai between", value1, value2, "szhuangtai");
            return (Criteria) this;
        }

        public Criteria andSzhuangtaiNotBetween(String value1, String value2) {
            addCriterion("szhuangtai not between", value1, value2, "szhuangtai");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shenqinggoumai
     *
     * @mbggenerated do_not_delete_during_merge Thu May 26 10:42:14 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}