package com.tushu.pojo;

public class Shenhe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenhe.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenhe.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenhe.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenhe.yijian
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String yijian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenhe.id
     *
     * @return the value of shenhe.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenhe.id
     *
     * @param id the value for shenhe.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenhe.uid
     *
     * @return the value of shenhe.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenhe.uid
     *
     * @param uid the value for shenhe.uid
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenhe.uname
     *
     * @return the value of shenhe.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenhe.uname
     *
     * @param uname the value for shenhe.uname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenhe.yijian
     *
     * @return the value of shenhe.yijian
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getYijian() {
        return yijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenhe.yijian
     *
     * @param yijian the value for shenhe.yijian
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setYijian(String yijian) {
        this.yijian = yijian == null ? null : yijian.trim();
    }
}