package com.tushu.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShukuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public ShukuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTbianhaoIsNull() {
            addCriterion("tbianhao is null");
            return (Criteria) this;
        }

        public Criteria andTbianhaoIsNotNull() {
            addCriterion("tbianhao is not null");
            return (Criteria) this;
        }

        public Criteria andTbianhaoEqualTo(String value) {
            addCriterion("tbianhao =", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoNotEqualTo(String value) {
            addCriterion("tbianhao <>", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoGreaterThan(String value) {
            addCriterion("tbianhao >", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoGreaterThanOrEqualTo(String value) {
            addCriterion("tbianhao >=", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoLessThan(String value) {
            addCriterion("tbianhao <", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoLessThanOrEqualTo(String value) {
            addCriterion("tbianhao <=", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoLike(String value) {
            addCriterion("tbianhao like", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoNotLike(String value) {
            addCriterion("tbianhao not like", value, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoIn(List<String> values) {
            addCriterion("tbianhao in", values, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoNotIn(List<String> values) {
            addCriterion("tbianhao not in", values, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoBetween(String value1, String value2) {
            addCriterion("tbianhao between", value1, value2, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTbianhaoNotBetween(String value1, String value2) {
            addCriterion("tbianhao not between", value1, value2, "tbianhao");
            return (Criteria) this;
        }

        public Criteria andTtypeIsNull() {
            addCriterion("ttype is null");
            return (Criteria) this;
        }

        public Criteria andTtypeIsNotNull() {
            addCriterion("ttype is not null");
            return (Criteria) this;
        }

        public Criteria andTtypeEqualTo(String value) {
            addCriterion("ttype =", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotEqualTo(String value) {
            addCriterion("ttype <>", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeGreaterThan(String value) {
            addCriterion("ttype >", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeGreaterThanOrEqualTo(String value) {
            addCriterion("ttype >=", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeLessThan(String value) {
            addCriterion("ttype <", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeLessThanOrEqualTo(String value) {
            addCriterion("ttype <=", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeLike(String value) {
            addCriterion("ttype like", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotLike(String value) {
            addCriterion("ttype not like", value, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeIn(List<String> values) {
            addCriterion("ttype in", values, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotIn(List<String> values) {
            addCriterion("ttype not in", values, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeBetween(String value1, String value2) {
            addCriterion("ttype between", value1, value2, "ttype");
            return (Criteria) this;
        }

        public Criteria andTtypeNotBetween(String value1, String value2) {
            addCriterion("ttype not between", value1, value2, "ttype");
            return (Criteria) this;
        }

        public Criteria andTnameIsNull() {
            addCriterion("tname is null");
            return (Criteria) this;
        }

        public Criteria andTnameIsNotNull() {
            addCriterion("tname is not null");
            return (Criteria) this;
        }

        public Criteria andTnameEqualTo(String value) {
            addCriterion("tname =", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotEqualTo(String value) {
            addCriterion("tname <>", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameGreaterThan(String value) {
            addCriterion("tname >", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameGreaterThanOrEqualTo(String value) {
            addCriterion("tname >=", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameLessThan(String value) {
            addCriterion("tname <", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameLessThanOrEqualTo(String value) {
            addCriterion("tname <=", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameLike(String value) {
            addCriterion("tname like", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotLike(String value) {
            addCriterion("tname not like", value, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameIn(List<String> values) {
            addCriterion("tname in", values, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotIn(List<String> values) {
            addCriterion("tname not in", values, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameBetween(String value1, String value2) {
            addCriterion("tname between", value1, value2, "tname");
            return (Criteria) this;
        }

        public Criteria andTnameNotBetween(String value1, String value2) {
            addCriterion("tname not between", value1, value2, "tname");
            return (Criteria) this;
        }

        public Criteria andTauthorIsNull() {
            addCriterion("tauthor is null");
            return (Criteria) this;
        }

        public Criteria andTauthorIsNotNull() {
            addCriterion("tauthor is not null");
            return (Criteria) this;
        }

        public Criteria andTauthorEqualTo(String value) {
            addCriterion("tauthor =", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorNotEqualTo(String value) {
            addCriterion("tauthor <>", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorGreaterThan(String value) {
            addCriterion("tauthor >", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorGreaterThanOrEqualTo(String value) {
            addCriterion("tauthor >=", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorLessThan(String value) {
            addCriterion("tauthor <", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorLessThanOrEqualTo(String value) {
            addCriterion("tauthor <=", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorLike(String value) {
            addCriterion("tauthor like", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorNotLike(String value) {
            addCriterion("tauthor not like", value, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorIn(List<String> values) {
            addCriterion("tauthor in", values, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorNotIn(List<String> values) {
            addCriterion("tauthor not in", values, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorBetween(String value1, String value2) {
            addCriterion("tauthor between", value1, value2, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTauthorNotBetween(String value1, String value2) {
            addCriterion("tauthor not between", value1, value2, "tauthor");
            return (Criteria) this;
        }

        public Criteria andTchubansheIsNull() {
            addCriterion("tchubanshe is null");
            return (Criteria) this;
        }

        public Criteria andTchubansheIsNotNull() {
            addCriterion("tchubanshe is not null");
            return (Criteria) this;
        }

        public Criteria andTchubansheEqualTo(String value) {
            addCriterion("tchubanshe =", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheNotEqualTo(String value) {
            addCriterion("tchubanshe <>", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheGreaterThan(String value) {
            addCriterion("tchubanshe >", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheGreaterThanOrEqualTo(String value) {
            addCriterion("tchubanshe >=", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheLessThan(String value) {
            addCriterion("tchubanshe <", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheLessThanOrEqualTo(String value) {
            addCriterion("tchubanshe <=", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheLike(String value) {
            addCriterion("tchubanshe like", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheNotLike(String value) {
            addCriterion("tchubanshe not like", value, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheIn(List<String> values) {
            addCriterion("tchubanshe in", values, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheNotIn(List<String> values) {
            addCriterion("tchubanshe not in", values, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheBetween(String value1, String value2) {
            addCriterion("tchubanshe between", value1, value2, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTchubansheNotBetween(String value1, String value2) {
            addCriterion("tchubanshe not between", value1, value2, "tchubanshe");
            return (Criteria) this;
        }

        public Criteria andTdateIsNull() {
            addCriterion("tdate is null");
            return (Criteria) this;
        }

        public Criteria andTdateIsNotNull() {
            addCriterion("tdate is not null");
            return (Criteria) this;
        }

        public Criteria andTdateEqualTo(Date value) {
            addCriterion("tdate =", value, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateNotEqualTo(Date value) {
            addCriterion("tdate <>", value, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateGreaterThan(Date value) {
            addCriterion("tdate >", value, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateGreaterThanOrEqualTo(Date value) {
            addCriterion("tdate >=", value, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateLessThan(Date value) {
            addCriterion("tdate <", value, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateLessThanOrEqualTo(Date value) {
            addCriterion("tdate <=", value, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateIn(List<Date> values) {
            addCriterion("tdate in", values, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateNotIn(List<Date> values) {
            addCriterion("tdate not in", values, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateBetween(Date value1, Date value2) {
            addCriterion("tdate between", value1, value2, "tdate");
            return (Criteria) this;
        }

        public Criteria andTdateNotBetween(Date value1, Date value2) {
            addCriterion("tdate not between", value1, value2, "tdate");
            return (Criteria) this;
        }

        public Criteria andTjiechuIsNull() {
            addCriterion("tjiechu is null");
            return (Criteria) this;
        }

        public Criteria andTjiechuIsNotNull() {
            addCriterion("tjiechu is not null");
            return (Criteria) this;
        }

        public Criteria andTjiechuEqualTo(String value) {
            addCriterion("tjiechu =", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuNotEqualTo(String value) {
            addCriterion("tjiechu <>", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuGreaterThan(String value) {
            addCriterion("tjiechu >", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuGreaterThanOrEqualTo(String value) {
            addCriterion("tjiechu >=", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuLessThan(String value) {
            addCriterion("tjiechu <", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuLessThanOrEqualTo(String value) {
            addCriterion("tjiechu <=", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuLike(String value) {
            addCriterion("tjiechu like", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuNotLike(String value) {
            addCriterion("tjiechu not like", value, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuIn(List<String> values) {
            addCriterion("tjiechu in", values, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuNotIn(List<String> values) {
            addCriterion("tjiechu not in", values, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuBetween(String value1, String value2) {
            addCriterion("tjiechu between", value1, value2, "tjiechu");
            return (Criteria) this;
        }

        public Criteria andTjiechuNotBetween(String value1, String value2) {
            addCriterion("tjiechu not between", value1, value2, "tjiechu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shuku
     *
     * @mbggenerated do_not_delete_during_merge Thu May 26 10:42:14 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}