package com.tushu.pojo;

import java.util.Date;

public class Shuku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.tbianhao
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String tbianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.ttype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String ttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.tname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.tauthor
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String tauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.tchubanshe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String tchubanshe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.tdate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private Date tdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuku.tjiechu
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    private String tjiechu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.id
     *
     * @return the value of shuku.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.id
     *
     * @param id the value for shuku.id
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.tbianhao
     *
     * @return the value of shuku.tbianhao
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTbianhao() {
        return tbianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.tbianhao
     *
     * @param tbianhao the value for shuku.tbianhao
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTbianhao(String tbianhao) {
        this.tbianhao = tbianhao == null ? null : tbianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.ttype
     *
     * @return the value of shuku.ttype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTtype() {
        return ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.ttype
     *
     * @param ttype the value for shuku.ttype
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTtype(String ttype) {
        this.ttype = ttype == null ? null : ttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.tname
     *
     * @return the value of shuku.tname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.tname
     *
     * @param tname the value for shuku.tname
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.tauthor
     *
     * @return the value of shuku.tauthor
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTauthor() {
        return tauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.tauthor
     *
     * @param tauthor the value for shuku.tauthor
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTauthor(String tauthor) {
        this.tauthor = tauthor == null ? null : tauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.tchubanshe
     *
     * @return the value of shuku.tchubanshe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTchubanshe() {
        return tchubanshe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.tchubanshe
     *
     * @param tchubanshe the value for shuku.tchubanshe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTchubanshe(String tchubanshe) {
        this.tchubanshe = tchubanshe == null ? null : tchubanshe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.tdate
     *
     * @return the value of shuku.tdate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public Date getTdate() {
        return tdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.tdate
     *
     * @param tdate the value for shuku.tdate
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTdate(Date tdate) {
        this.tdate = tdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuku.tjiechu
     *
     * @return the value of shuku.tjiechu
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public String getTjiechu() {
        return tjiechu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuku.tjiechu
     *
     * @param tjiechu the value for shuku.tjiechu
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    public void setTjiechu(String tjiechu) {
        this.tjiechu = tjiechu == null ? null : tjiechu.trim();
    }
}