package com.tushu.mapper;

import com.tushu.pojo.Bumen;
import com.tushu.pojo.BumenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BumenMapper { 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int countByExample(BumenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByExample(BumenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insert(Bumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insertSelective(Bumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    List<Bumen> selectByExample(BumenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    Bumen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") Bumen record, @Param("example") BumenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExample(@Param("record") Bumen record, @Param("example") BumenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKeySelective(Bumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bumen
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKey(Bumen record);
}