package com.tushu.mapper;

import com.tushu.pojo.Jieyue;
import com.tushu.pojo.JieyueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JieyueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int countByExample(JieyueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByExample(JieyueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insert(Jieyue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insertSelective(Jieyue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    List<Jieyue> selectByExample(JieyueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    Jieyue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") Jieyue record, @Param("example") JieyueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExample(@Param("record") Jieyue record, @Param("example") JieyueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKeySelective(Jieyue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jieyue
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKey(Jieyue record);
}