package com.tushu.mapper;

import com.tushu.pojo.Shenhe;
import com.tushu.pojo.ShenheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShenheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int countByExample(ShenheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByExample(ShenheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insert(Shenhe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insertSelective(Shenhe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    List<Shenhe> selectByExample(ShenheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    Shenhe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") Shenhe record, @Param("example") ShenheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExample(@Param("record") Shenhe record, @Param("example") ShenheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKeySelective(Shenhe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenhe
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKey(Shenhe record);
}