package com.tushu.mapper;

import com.tushu.pojo.Shenqinggoumai;
import com.tushu.pojo.ShenqinggoumaiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShenqinggoumaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int countByExample(ShenqinggoumaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByExample(ShenqinggoumaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insert(Shenqinggoumai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insertSelective(Shenqinggoumai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    List<Shenqinggoumai> selectByExample(ShenqinggoumaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    Shenqinggoumai selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") Shenqinggoumai record, @Param("example") ShenqinggoumaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExample(@Param("record") Shenqinggoumai record, @Param("example") ShenqinggoumaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKeySelective(Shenqinggoumai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenqinggoumai
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKey(Shenqinggoumai record);
}