package com.tushu.mapper;

import com.tushu.pojo.Shuku;
import com.tushu.pojo.ShukuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShukuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int countByExample(ShukuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByExample(ShukuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insert(Shuku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int insertSelective(Shuku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    List<Shuku> selectByExample(ShukuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    Shuku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") Shuku record, @Param("example") ShukuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByExample(@Param("record") Shuku record, @Param("example") ShukuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKeySelective(Shuku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuku
     *
     * @mbggenerated Thu May 26 10:42:14 CST 2016
     */
    int updateByPrimaryKey(Shuku record);
}